#!/bin/bash
set -eux

# Construct our Ansible Collection in a temporary "_build" directory.

TOPDIR=$(dirname "$(readlink -f "$0")")

cd $TOPDIR

rm -rf _build
mkdir _build
cd _build

mkdir plugins
cp $TOPDIR/COPYING .
cp -r $TOPDIR/meta/ .
cp -r $TOPDIR/library/ plugins/modules
cp -r $TOPDIR/module_utils/ plugins/module_utils/


# Make our dockpulp_common imports compatible with Ansible Collections.
sed -i \
  -e  's/from ansible.module_utils.dockpulp_common/from ansible_collections.release_engineering.dockpulp_ansible.plugins.module_utils.dockpulp_common/' \
  plugins/modules/*.py

# Convert README from reStructuredText to Markdown.
# Ansible Galaxy's Markdown engine plays best with markdown_strict.
pandoc $TOPDIR/README.rst -f rst -t markdown_strict -o README.md

# Determine our semver-compatible version number from Git.
BASE_REF="${GITHUB_BASE_REF:-HEAD}"
BASE_COMMIT=$(git rev-list --max-parents=0 $BASE_REF)
COMMIT_COUNT=$(($(git rev-list --count $BASE_COMMIT..HEAD) - 1))

# Versions will always be 0.1.XXX.
VERSION="0.1.${COMMIT_COUNT}"

sed $TOPDIR/galaxy.yml -e "s/{{ version }}/$VERSION/" > galaxy.yml

ansible-galaxy collection build
